version: '3.1'

services:
  db:
    image: postgres:12
    command: postgres -c max_prepared_transactions=10
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
  client:
    build: .
    links:
      - "db"
    stdin_open: true
    tty: true
